---
- name: configure an anonymous ftp upload server
  hosts: anonftp
  tasks:
    - name: install vsftpd
      become: true
      block:
      - zypper:
          name: vsftpd
          state: latest
          update_cache: true
        notify: restart vsftpd
      - systemd:
          name: vsftpd
          state: started
          enabled: true
      - copy:
          src: ./files/anonftp_vsftpd.conf
          dest: /etc/vsftpd.conf
        notify: restart vsftpd
      - file:
          path: /srv/anonroot
          state: directory
          owner: root
          group: root
          mode: '0755'
        notify: restart vsftpd
      - file:
          path: /srv/anonroot/incoming
          state: directory
          owner: ftp
          group: users
          mode: '0755'
        notify: restart vsftpd

  handlers:
  - name: restart vsftpd
    become: true
    systemd:
      name: vsftpd
      state: restarted
      daemon_reload: yes
